"""
Exercise 4 — Answers
====================
Fill this in after running exercise4_mcp_client.py.
"""

# ── Basic results ──────────────────────────────────────────────────────────

# Tool names as shown in "Discovered N tools" output.
TOOLS_DISCOVERED = ['search_venues', 'get_venue_details']

QUERY_1_VENUE_NAME    = "The Haymarket Vaults"
QUERY_1_VENUE_ADDRESS = "1 Dalry Road, Edinburgh"
QUERY_2_FINAL_ANSWER  = "It seems there are no Edinburgh venues currently available that can accommodate 300 people with vegan options. Would you like to:\n\n1. Try a lower minimum capacity (e.g., 250 people)?\n2. Check for venues without vegan requirements?\n3. Verify availability at a specific venue name?\n\nLet me know how you'd like to proceed."

# ── The experiment ─────────────────────────────────────────────────────────
# Required: modify venue_server.py, rerun, revert.

EX4_EXPERIMENT_DONE = True   # True or False

# What changed, and which files did or didn't need updating? Min 30 words.
EX4_EXPERIMENT_RESULT = """
The answer is the same "The Haymarket Vaults" pub. 
But if we look at thinking process and the results of search_venues tool we see only one pub The Haymarket Vaults.
This is correct as we changed The Albanach's status from 'available' to 'full'.
For this experiment we had to change only mcp_venue_server.py because this file contains the database 
with information about pub status. We didn't change the prompt as LangGRagh agent gets the results 
from MCP Server tools/functions which get arguments from database.
"""

# ── MCP vs hardcoded ───────────────────────────────────────────────────────

LINES_OF_TOOL_CODE_EX2 = 360   # count in exercise2_langgraph.py
LINES_OF_TOOL_CODE_EX4 = 190   # count in exercise4_mcp_client.py

# What does MCP buy you beyond "the tools are in a separate file"? Min 30 words.
MCP_VALUE_PROPOSITION = """
MCP buys us Dynamic Discovery. Instead of hardcoding tools into every agent, the agents ask the server "What can you do?" at runtime.
Plus MCP can be the "Shared Layer". It allows both LangGraph and Rasa to use the exact same venue data, 
ensuring they never disagree on which pubs are available.
"""

# ── PyNanoClaw architecture — SPECULATION QUESTION ─────────────────────────
#
# (The variable below is still called WEEK_5_ARCHITECTURE because the
# grader reads that exact name. Don't rename it — but read the updated
# prompt: the question is now about PyNanoClaw, the hybrid system the
# final assignment will have you build.)
#
# This is a forward-looking, speculative question. You have NOT yet seen
# the material that covers the planner/executor split, memory, or the
# handoff bridge in detail — that is what the final assignment (releases
# 2026-04-18) is for. The point of asking it here is to check that you
# have read PROGRESS.md and can imagine how the Week 1 pieces grow into
# PyNanoClaw.
#
# Read PROGRESS.md in the repo root. Then write at least 5 bullet points
# describing PyNanoClaw as you imagine it at final-assignment scale.
#
# Each bullet should:
#   - Name a component (e.g. "Planner", "Memory store", "Handoff bridge",
#     "Rasa MCP gateway")
#   - Say in one clause what that component does and which half of
#     PyNanoClaw it lives in (the autonomous loop, the structured agent,
#     or the shared layer between them)
#
# You are not being graded on getting the "right" architecture — there
# isn't one right answer. You are being graded on whether your description
# is coherent and whether you have thought about which Week 1 file becomes
# which PyNanoClaw component.
#
# Example of the level of detail we want:
#   - The Planner is a strong-reasoning model (e.g. Nemotron-3-Super or
#     Qwen3-Next-Thinking) that takes the raw task and produces an ordered
#     list of subgoals. It lives upstream of the ReAct loop in the
#     autonomous-loop half of PyNanoClaw, so the Executor never sees an
#     ambiguous task.

WEEK_5_ARCHITECTURE = """
- The Planner: This component uses a strong-reasoning model to break down complex user requests into a structured list of subgoals
 and lives upstream of the ReAct loop in the autonomous-loop half of PyNanoClaw.
- The Executor: This fast-acting worker (an evolution of research_agent.py) performs the actual tool calls
to fulfill the specific subgoals generated by the Planner and lives inside the autonomous-loop half.
- The Handoff Bridge: This routing layer delegates high-stakes human conversations to the Rasa half or research tasks 
back to the LangGraph half and lives as the connective link between the autonomous and structured agent halves.
- The Memory Store: This persistent layer uses filesystem-backed or vector storage to save learned information 
and context across turns, living in the shared layer or alongside the structured agent for RAG capabilities.
- The Shared MCP Server: This central hub (based on mcp_venue_server.py) hosts all venue and search tools 
for dynamic discovery and lives in the shared layer accessible to both the autonomous and structured agents.
"""

# ── The guiding question ───────────────────────────────────────────────────
# Which agent for the research? Which for the call? Why does swapping feel wrong?
# Must reference specific things you observed in your runs. Min 60 words.

GUIDING_QUESTION_ANSWER = """
We need use the LangGraph agent for research and the Rasa agent for the manager call. 
Swapping them feels wrong because LangGraph is "probabilistic." 
As I observed in Exercise 2, when a request is out-of-scope, the LLM improvises a helpful answer. 
While this is great for research, it is dangerous for a high-stakes call where the agent might "hallucinate" 
and agree to a deposit that exceeds Rod's £300 limit just to be helpful. 

In contrast, Rasa Pro CALM is "deterministic." As seen in Exercise 3, it uses Python guards to stay strictly within business boundaries. 
Rasa is perfect for the call because it cannot negotiate away the rules, 
but it would be too rigid for research because it cannot improvise when it encounters messy data or unexpected questions.
"""